### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by diogobalseiro** [Farfetch/network-monitor-ios#15]
## Issue Report

This repo should support Swift Package Manager.

## Expected Behavior

Users should be able to install this tool via SPM.

## Actual Behavior

Users are unable to install this tool via SPM.

## Steps to Reproduce the Issue

Follow the [documentation](https://swift.org/package-manager/) to properly support SPM.

**Comment by FranciscoAmado** [comment]
🙋🏻‍♂️ Will pick up on this in the following days

**Comment by FranciscoAmado** [comment]
Solved in #16
