### ISSUE TITLE
No automatic cocoapod spec publishing exists

### ISSUE THREAD

**Issue by diogobalseiro** [Farfetch/network-monitor-ios#7]
## Issue Report

No automatic cocoapod spec publishing exists today.

## Expected Behavior

After a code push to master, if a new cocoapod spec exists, then it should be tagged and published automatically.

## Actual Behavior

After a code push to master, no cocoapod spec is pushed.

## Steps to Reproduce the Issue

Simply merge a pull request.

**Comment by xnzz** [comment]
Take a look: [Deploy to Cocoapod Action](https://github.com/marketplace/actions/deploy-to-cocoapod-action)

**Comment by diogobalseiro** [comment]
Fixed in https://github.com/Farfetch/network-monitor-ios/pull/11
